-- fixture_mainnet_registry_evt_record_set
-- Generated by `nuthatch emit dune` from `registry__record_set` (RFC-0055). Regenerate; do not edit.
--
-- A record was set.
-- Grain: one row per RecordSet event
--
-- Columns:
--   contract_address varbinary: renamed from `address`
--   evt_tx_hash varbinary: renamed from `tx_hash`
--   evt_index bigint: renamed from `log_index`
--   evt_block_time timestamp: renamed from `block_timestamp`
--   evt_block_date date: the UTC date of `block_timestamp`
--   evt_block_number bigint: renamed from `block_number`
--   evt_block_hash varbinary: renamed from `block_hash`
--   label varbinary: The record label. Holds the keccak-256 hash of the indexed value, not the value.
--   node varbinary: Namehash of the record.
--   data varbinary: Raw record payload.
--   name varchar: Display name.
--   enabled boolean: Whether the record resolves.
--   meta varchar: Owner and expiry, as JSON.
SELECT
    from_hex(substr(address, 3)) AS contract_address,
    from_hex(substr(tx_hash, 3)) AS evt_tx_hash,
    cast(log_index as bigint) AS evt_index,
    cast(from_unixtime(block_timestamp, 'UTC') as timestamp) AS evt_block_time,
    cast(from_unixtime(block_timestamp, 'UTC') as date) AS evt_block_date,
    cast(block_number as bigint) AS evt_block_number,
    from_hex(substr(block_hash, 3)) AS evt_block_hash,
    from_hex(substr("label", 3)) AS "label",
    from_hex(substr("node", 3)) AS "node",
    from_hex(substr("data", 3)) AS "data",
    "name" AS "name",
    case "enabled" when 'true' then true when 'false' then false end AS "enabled",
    "meta" AS "meta"
FROM dune.fixture_ns.registry__record_set
