-- fixture_nest_mainnet_view_top_holders
-- Generated by `nuthatch emit dune` from view `top_holders` in `views/10-top_holders.sql` (RFC-0055 S3). Regenerate; do not edit.
--
-- The ten largest holders of vault shares.
--
-- Columns: holder, shares
WITH
    "vault__transfer" AS (SELECT *, TRY_CAST("value" AS DECIMAL(38,0)) AS "value_dec", ("value" IS NOT NULL AND TRY_CAST("value" AS DECIMAL(38,0)) IS NULL) AS "value_overflow" FROM dune.fixture_ns.vault__transfer)
SELECT
    "to" AS "holder",
    sum("value_dec") AS "shares"
FROM "vault__transfer"
GROUP BY 1
ORDER BY "shares" DESC NULLS LAST
LIMIT 10
