-- fixture_nest_mainnet_pool_evt_swap
-- Generated by `nuthatch emit dune` from `pool__swap` (RFC-0055). Regenerate; do not edit.
--
-- Swaps against the pool. Signed amounts are from the pool's side.
-- Grain: one row per Swap event
--
-- Columns:
--   contract_address varbinary: renamed from `address`
--   evt_tx_hash varbinary: renamed from `tx_hash`
--   evt_index bigint: renamed from `log_index`
--   evt_block_time timestamp: renamed from `block_timestamp`
--   evt_block_date date: the UTC date of `block_timestamp`
--   evt_block_number bigint: renamed from `block_number`
--   evt_block_hash varbinary: renamed from `block_hash`
--   amount0 int256: Token0 delta, signed.
--   amount0_raw varchar: the exact decimal text of `amount0`
--   liquidity uint256: In-range liquidity after the swap.
--   liquidity_raw varchar: the exact decimal text of `liquidity`
--   delta int256: Signed 128-bit delta.
--   delta_raw varchar: the exact decimal text of `delta`
--   sqrtPriceX96 uint256: Square root price, Q64.96.
--   sqrtPriceX96_raw varchar: the exact decimal text of `sqrtPriceX96`
--   tick bigint: Tick after the swap.
--   fee bigint: Pool fee in hundredths of a bip.
--   deadline uint256: Unix deadline.
--   offset bigint
SELECT
    from_hex(substr(address, 3)) AS contract_address,
    from_hex(substr(tx_hash, 3)) AS evt_tx_hash,
    cast(log_index as bigint) AS evt_index,
    cast(from_unixtime(block_timestamp, 'UTC') as timestamp) AS evt_block_time,
    cast(from_unixtime(block_timestamp, 'UTC') as date) AS evt_block_date,
    cast(block_number as bigint) AS evt_block_number,
    from_hex(substr(block_hash, 3)) AS evt_block_hash,
    cast("amount0" as int256) AS "amount0",
    "amount0" AS "amount0_raw",
    cast("liquidity" as uint256) AS "liquidity",
    "liquidity" AS "liquidity_raw",
    cast("delta" as int256) AS "delta",
    "delta" AS "delta_raw",
    cast("sqrtPriceX96" as uint256) AS "sqrtPriceX96",
    "sqrtPriceX96" AS "sqrtPriceX96_raw",
    cast("tick" as bigint) AS "tick",
    cast("fee" as bigint) AS "fee",
    cast("deadline" as uint256) AS "deadline",
    cast("offset" as bigint) AS "offset"
FROM dune.fixture_ns.pool__swap
