-- fixture_nest_mainnet_vault_evt_paused
-- Generated by `nuthatch emit dune` from `vault__paused` (RFC-0055). Regenerate; do not edit.
--
-- The vault was paused.
--
-- Columns:
--   contract_address varbinary: renamed from `address`
--   evt_tx_hash varbinary: renamed from `tx_hash`
--   evt_index bigint: renamed from `log_index`
--   evt_block_time timestamp: renamed from `block_timestamp`
--   evt_block_date date: the UTC date of `block_timestamp`
--   evt_block_number bigint: renamed from `block_number`
--   evt_block_hash varbinary: renamed from `block_hash`
--   account varbinary
SELECT
    from_hex(substr(address, 3)) AS contract_address,
    from_hex(substr(tx_hash, 3)) AS evt_tx_hash,
    cast(log_index as bigint) AS evt_index,
    cast(from_unixtime(block_timestamp, 'UTC') as timestamp) AS evt_block_time,
    cast(from_unixtime(block_timestamp, 'UTC') as date) AS evt_block_date,
    cast(block_number as bigint) AS evt_block_number,
    from_hex(substr(block_hash, 3)) AS evt_block_hash,
    from_hex(substr("account", 3)) AS "account"
FROM dune.fixture_ns.vault__paused
