-- fixture_nest_mainnet_vault_evt_transfer
-- Generated by `nuthatch emit dune` from `vault__transfer` (RFC-0055). Regenerate; do not edit.
--
-- ERC-20 transfers of the vault share token.
-- Grain: one row per Transfer event
--
-- Columns:
--   contract_address varbinary: renamed from `address`
--   evt_tx_hash varbinary: renamed from `tx_hash`
--   evt_index bigint: renamed from `log_index`
--   evt_block_time timestamp: renamed from `block_timestamp`
--   evt_block_date date: the UTC date of `block_timestamp`
--   evt_block_number bigint: renamed from `block_number`
--   evt_block_hash varbinary: renamed from `block_hash`
--   from varbinary: Sender of the shares.
--   to varbinary: Receiver of the shares.
--   value uint256: Shares moved, in base units.
--   value_raw varchar: the exact decimal text of `value`
SELECT
    from_hex(substr(address, 3)) AS contract_address,
    from_hex(substr(tx_hash, 3)) AS evt_tx_hash,
    cast(log_index as bigint) AS evt_index,
    cast(from_unixtime(block_timestamp, 'UTC') as timestamp) AS evt_block_time,
    cast(from_unixtime(block_timestamp, 'UTC') as date) AS evt_block_date,
    cast(block_number as bigint) AS evt_block_number,
    from_hex(substr(block_hash, 3)) AS evt_block_hash,
    from_hex(substr("from", 3)) AS "from",
    from_hex(substr("to", 3)) AS "to",
    cast("value" as uint256) AS "value",
    "value" AS "value_raw"
FROM dune.fixture_ns.vault__transfer
