#!/usr/bin/env bash
# Regenerate scripts/gate/alloc-queries.tsv from kittiwake's source. Run on purpose, review the diff.
#
#   scripts/gate/collect-queries.sh [kittiwake-checkout] > scripts/gate/alloc-queries.tsv
#
# Compiles scripts/gate/collect/main.rs against a copy of kittiwake's crates/read/src/sql.rs with
# plain rustc (edition 2024, no cargo, no dependencies). Statements built in sql.rs refresh
# themselves; the ones main.rs marks `inline` are hand copies, so re-read those call sites too:
#   grep -rn 'NestId::Alloc' <kittiwake>/crates --include='*.rs' | grep -v /tests/
# Lodestar itself sends nothing to the nest: its dashboard reads kittiwake's API, so its share of
# the set is what kittiwake's read routes ask on its behalf.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
kw=${1:-$HOME/Projects/kittiwake}
src=$kw/crates/read/src/sql.rs
db=$kw/crates/db/src/lib.rs
[ -f "$src" ] || { echo "collect-queries: no $src" >&2; exit 2; }
[ -f "$db" ] || { echo "collect-queries: no $db" >&2; exit 2; }
command -v rustc >/dev/null || { echo "collect-queries: rustc not on PATH" >&2; exit 2; }

excluded=$(sed -n 's/^pub const INDEXERS_EXCLUDED: &str = "\(0x[0-9a-f]*\)";$/\1/p' "$db")
[ -n "$excluded" ] || { echo "collect-queries: INDEXERS_EXCLUDED not found in $db" >&2; exit 1; }

work=$(mktemp -d "${TMPDIR:-/tmp}/collect-queries.XXXXXX")
trap 'rm -rf "$work"' EXIT
cp "$here/collect/main.rs" "$work/main.rs"
# sql.rs re-exports one constant from kittiwake_db; inline it so the file stands alone.
sed "s|^pub use kittiwake_db::INDEXERS_EXCLUDED;|pub const INDEXERS_EXCLUDED: \&str = \"$excluded\";|" \
  "$src" > "$work/sql.rs"
grep -q 'kittiwake_db' "$work/sql.rs" && { echo "collect-queries: sql.rs still names kittiwake_db" >&2; exit 1; }

rustc --edition 2024 -O -o "$work/collect" "$work/main.rs" >&2

# The checkout's commit, read from .git rather than asked of git, so a bare copy still works.
kw_rev=unknown
if [ -f "$kw/.git/HEAD" ]; then
  head_line=$(cat "$kw/.git/HEAD")
  case "$head_line" in
    ref:\ *)
      ref=${head_line#ref: }
      if [ -f "$kw/.git/$ref" ]; then
        kw_rev=$(cut -c1-12 "$kw/.git/$ref")
      elif [ -f "$kw/.git/packed-refs" ]; then
        kw_rev=$(awk -v r="$ref" '$2 == r { print substr($1, 1, 12) }' "$kw/.git/packed-refs")
      fi
      ;;
    *) kw_rev=$(printf '%s' "$head_line" | cut -c1-12) ;;
  esac
fi
: "${kw_rev:=unknown}"
cat <<EOF
# The allocations nest's query set: what Lodestar (via kittiwake's read API) and kittiwake's jobs
# send to its /sql. Generated by scripts/gate/collect-queries.sh from kittiwake $kw_rev on $(date -u +%Y-%m-%d).
# Do not hand-edit; change scripts/gate/collect/main.rs and regenerate.
# id<TAB>consumer<TAB>call site<TAB>sql
EOF
"$work/collect"
